version: '3'
services:
  frpc:
    image: snowdreamtech/frpc:0.38.0
    container_name: frpc
    privileged: true
    restart: always
    volumes:
      - /Users/zhangtao/Applications/space/docker/frp/frpc.ini:/etc/frp/frpc.ini
    network_mode: "host"