# https://docs.gitea.io/zh-cn/install-with-docker/#mysql-%E6%95%B0%E6%8D%AE%E5%BA%93
# Gitea 是一个开源社区驱动的轻量级代码托管解决方案，后端采用 Go 编写，采用 MIT 许可证.
version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.18.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql      #数据库类型
      - GITEA__database__HOST=db:3306       #数据库端口
      - GITEA__database__NAME=gitea         #数据库db名称
      - GITEA__database__USER=root          #数据库用户
      - GITEA__database__PASSWD=gitea       #数据库密码
    restart: always
    networks:
      - gitea
    volumes:
      - /volume1/docker/gitea:/data                       #gitea数据挂载宿主机
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    links:
      - mysql5_7:mysql5_7
