# 具体配置查看官方：https://github.com/nacos-group/nacos-docker
# init sql script: https://github.com/alibaba/nacos/blob/master/distribution/conf/mysql-schema.sql
version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-standalone-mysql
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
    volumes:
      - /opt/docker_volumes/nacos2/standalone-logs/:/home/nacos/logs
      - /opt/docker_volumes/nacos2/init.d/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"