# redis管理
# 官方wiki：https://github.com/ngbdf/redis-manager/wiki
# 端口号：8182
# 默认密码：admin/admin
version: '3'
services:
  redis_manager:
    image: reasonduan/redis-manager
    container_name: redis-manager
    privileged: true
    restart: always
    environment:
      - DATASOURCE_DATABASE=redis_manager
      - DATASOURCE_URL=jdbc:mysql://192.168.128.129:3306/redis_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=czxk2020!
    network_mode: "host"