version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine        # 镜像`rabbitmq:3-management` 【 注：该版本包含了web控制页面和delay插件 】
    container_name: rabbitmq                      # 容器名为'rabbitmq'
    hostname: rabbitmq                            # 主机名为'rabbitmq'
    restart: always                               # 指定容器退出后的重启策略为始终重启
    platform: linux/amd64                         # 指定平台
    environment:                                  # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      RABBITMQ_DEFAULT_VHOST: my_vhost            # 主机名
      RABBITMQ_DEFAULT_USER: root                 # 登录账号
      RABBITMQ_DEFAULT_PASS: 123456               # 登录密码
      # RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.5 #内存比例
    volumes:                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/Users/zhangtao/Applications/docker/rabbitmq/data:/var/lib/rabbitmq"
    ports:                                        # 映射端口
      - "5672:5672"
      - "15672:15672"
    deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1024M
          reservations:
            cpus: '0.25'
            memory: 512M