version: '3'
services:
  mcms:
    image: mingsoft/mcms
    container_name: mcms
    privileged: true
    platform: linux/amd64
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    command: >
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      --lower-case-table-names=1
      --query-cache-type=1
      --query-cache-size=600000
      --max-connections=1000
    ports:
      - "3306:3306"
      - "8080:8080"
    restart: always
