version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3380:80
    environment:
      - PMA_HOST=192.168.31.200
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_ARBITRARY=1