---

#https://hub.docker.com/r/kasmweb/firefox
#######################################   启动后浏览器直接访问：https://127.0.0.1:6901/  ######################################################################
#######################################   启动后浏览器直接访问用户名：kasm_user           ######################################################################
#######################################   启动后浏览器直接访问密码：password              ######################################################################
version: "3"
services:
  firefox:
    image: kasmweb/firefox:1.12.0
    container_name: firefox
    environment:
      - VNC_PW=password
    ports:
      - "6901:6901"
    shm_size: "512m"