version: '3'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    privileged: true
    restart: always
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000