version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - /opt/docker_volumes/zookeeper/data:/data
    ports:
      - "2181:2181"
       
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.128.129
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /opt/docker_volumes/kafka:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
 
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9020:9000"
    environment:
      ZK_HOSTS: zookeeper:2181