version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-docker-compose.yaml
    restart: always
    volumes:
      - /opt/docker_volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090